# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
DOMAIN=apt.emulab.net
# DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
MACHINES=( "apt185" "apt161" "apt141" "apt181" "apt145" "apt187" "apt146" "apt156" "apt173" "apt153")
# MACHINES=( "c240g5-110231" )
USER=alclev
# ------------------------------------------
