# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
# DOMAIN=apt.emulab.net
DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
MACHINES=( "clgpu016" "clgpu013" "clgpu009" "clgpu017" "clgpu021")
# MACHINES=( "c240g5-110231" )
USER=alclev
# ------------------------------------------
