# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
DOMAIN=apt.emulab.net
# DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
MACHINES=( "apt150" "apt176" "apt177" "apt161" "apt180" "apt083" "apt072" "apt081" "apt138" "apt139" )
USER=alclev
# ------------------------------------------
