#include <csignal>
#include <filesystem>
#include <functional>
#include <random>
#include <string>
#include <barrier>

#include "cfg.h"
#include "dag.h"
#include "mu/mu_impl.h"
#include "romulus/cfg.h"
#include "romulus/common.h"
#include "romulus/connection_manager.h"
#include "romulus/device.h"
#include "romulus/memblock.h"
#include "romulus/qp_pol.h"
#include "romulus/stats.h"
#include "romulus/util.h"
#include "state.h"
#include "util.h"

#define PAXOS_NS paxos_st
constexpr uint32_t kNumProposals = 8092;

void signal_handler(int signum) {
  if (signum == SIGTSTP) {
    write(STDOUT_FILENO, "SIGINT caught\n", 14);
    dump_requested_.store(true, std::memory_order_relaxed);
  }
}

int main(int argc, char* argv[]) {
  struct sigaction sa{};
  sa.sa_handler = signal_handler;
  sigemptyset(&sa.sa_mask);
  sa.sa_flags = 0;
  sigaction(SIGTSTP, &sa, nullptr);

  PinToCore(0);

  ROMULUS_STOPWATCH_DECLARE();
  romulus::INIT();
  auto args = std::make_shared<romulus::ArgMap>();
  args->import(romulus::ARGS);
  args->import(romulus::EXTRA_ARGS);
  args->parse(argc, argv);
  INGEST_ARGS(args);

  // Print configuration.
  ROMULUS_INFO("Experimental Configuration:");
  ROMULUS_INFO("!> [CONF] hostname={}", hostname);
  ROMULUS_INFO("!> [CONF] host id={}", id);
  ROMULUS_INFO("!> [CONF] registry ip={}", registry_ip);
  ROMULUS_INFO("!> [CONF] output file={}", output_file);
  ROMULUS_INFO("!> [CONF] testtime={}_s", testtime.count());
  ROMULUS_INFO("!> [CONF] device name={}", dev_name);
  ROMULUS_INFO("!> [CONF] device port={}", dev_port);
  ROMULUS_INFO("!> [CONF] transport type={}", transport);
  ROMULUS_INFO("!> [CONF] loop={}", loop);
  ROMULUS_INFO("!> [CONF] capacity={}", capacity);
  ROMULUS_INFO("!> [CONF] buf_size={}", buf_size);
  ROMULUS_INFO("!> [CONF] sleep={}_ms", sleep.count());
  ROMULUS_INFO("!> [CONF] leader_fixed={}", leader_fixed);
  ROMULUS_INFO("!> [CONF] policy={}", policy);
  ROMULUS_INFO("!> [CONF] duration={}_ms", duration.count());
  ROMULUS_INFO("!> [CONF] system_size={}", system_size);
  ROMULUS_INFO("!> [CONF] cpu_enabled={}", cpu_enabled);
  ROMULUS_INFO("!> [CONF] gpu_enabled={}", gpu_enabled);
  ROMULUS_INFO("!> [CONF] mode={}", mode);
  INIT_CONSENSUS(transport_flag, buf_size, mach_map);
  FILL_PROPOSALS();

  std::function<void(void)> init = SYNC_NODES;
  std::function<void(void)> exec = EXEC_LATENCY;
  std::function<void(void)> done = DONE_LATENCY;
  std::function<void(std::ofstream&)> calc = CALC_LATENCY;
  std::function<void(void)> reset = RESET;

  init();

  // Assuming commit_handler will be multiple threads
  // Different threads share the same state.
  // Create the random matrices during initialization
  std::cout << "[1/4] Initializing DAG Generator..." << std::endl;
  DagGenerator builder;
  State<float> initstate;
  initstate.populate_random_state_matrix(1, 100);

  // [Alex] should the workload be generated here?
  // Or we will work on the workload buffer generated by MU
  // Modify the following lines to read the buffer
  // WorkloadGenerator wg;
  // std::vector<op> ops = wg.generate(100, 5);

  std::atomic<bool> handler_running = true;
  std::barrier commit_barrier(2);
  ROMULUS_INFO("Initialization is finished. Launching commit thread...");
  
  auto commit_handler = std::thread([&]() {
    PinToCore(1);

    while (handler_running.load(std::memory_order_relaxed) == true) {
      // Wait for the main thread to signal that a batch of proposals has been sent
      commit_barrier.arrive_and_wait();
      // Need to do a quick check after all that wait time
      if (handler_running.load(std::memory_order_relaxed) == false) {
        break;
      }
      // TODO: CPU + SERIAL execution
      if(cpu_enabled && (mode == "SERIAL")) {
        builder.build_dag(ops);
        auto& dag = builder.get_dag();
        std::cout << "Done. Nodes in DAG: " << dag.size() << std::endl;

        std::cout << "[2/4] Sorting DAG into parallel levels..." << std::endl;
        auto levels = Scheduler::get_levels(dag);
        Scheduler::print(levels); 

        std::cout << "[3/4] Initializing CPU Executor and Workspaces..." << std::endl;
        CpuExecutor executor(ROWS, COLS);
        executor.load_state(initstate); 

        std::cout << "[4/4] Executing on CPU (Multi-threaded OpenMP)..." << std::endl;
        executor.run_sequential(dag);

        std::cout << "SUCCESS: CPU Workload completed." << std::endl;
      }
      // TODO: CPU + DAG execution
      if(cpu_enabled && (mode == "DAG")){
        builder.build_dag(ops);
        auto& dag = builder.get_dag();
        std::cout << "Done. Nodes in DAG: " << dag.size() << std::endl;

        std::cout << "[2/4] Sorting DAG into parallel levels..." << std::endl;
        auto levels = Scheduler::get_levels(dag);
        Scheduler::print(levels); 

        std::cout << "[3/4] Initializing CPU Executor and Workspaces..." << std::endl;
        CpuExecutor executor(ROWS, COLS);
        executor.load_state(initstate); 

        std::cout << "[4/4] Executing on CPU (Multi-threaded OpenMP)..." << std::endl;
        executor.run(dag, levels);

        std::cout << "SUCCESS: CPU Workload completed." << std::endl;
      }
      // TODO: GPU + SERIAL execution
      if(gpu_enabled && (mode == "SERIAL")) {
        builder.build_dag(ops);
        auto& dag = builder.get_dag();
        std::cout << "Done. Nodes in DAG: " << dag.size() << std::endl;

        std::cout << "[2/4] Sorting DAG into parallel levels..." << std::endl;
        auto levels = Scheduler::get_levels(dag);
        
        Scheduler::print(levels); 

        std::cout << "[3/4] Allocating VRAM and creating streams..." << std::endl;
        GpuExecutor executor(ROWS, COLS);
        executor.load_state(initstate);
        executor.prepare_dag(dag); 

        std::cout << "[4/4] Executing on GPU..." << std::endl;
        executor.run_sequential(dag); // sequential execution of DAGs

        std::cout << "SUCCESS: Workload completed." << std::endl;
      }
      // TODO: GPU + DAG execution
      if(gpu_enabled && (mode == "DAG")) {
        builder.build_dag(ops);
        auto& dag = builder.get_dag();
        std::cout << "Done. Nodes in DAG: " << dag.size() << std::endl;

        std::cout << "[2/4] Sorting DAG into parallel levels..." << std::endl;
        auto levels = Scheduler::get_levels(dag);
        
        Scheduler::print(levels); 

        std::cout << "[3/4] Allocating VRAM and creating streams..." << std::endl;
        GpuExecutor executor(ROWS, COLS);
        executor.load_state(initstate);
        executor.prepare_dag(dag); 

        std::cout << "[4/4] Executing on GPU..." << std::endl;
        executor.run(dag, levels);

        std::cout << "SUCCESS: Workload completed." << std::endl;        
      }
    }
  });

  ROMULUS_INFO("Starting latency test");
  // size_t iterations = 0;
  size_t last_offload_idx = 0;
  DagGenerator dag_generator;
  uint32_t fuo = 0;

  std::cout << "Wait some time" << std::endl;
  std::this_thread::sleep_for(std::chrono::seconds(2 + system_size - id));

  auto testtime_us =
      std::chrono::duration_cast<std::chrono::microseconds>(testtime);
  ROMULUS_STOPWATCH_BEGIN();
  size_t iterations = 0;
  while (ROMULUS_STOPWATCH_RUNTIME(ROMULUS_MICROSECONDS) <
         static_cast<uint64_t>(testtime_us.count())) {
    for (uint32_t i = 0; i < loop; ++i) {
      // Fixed leader node0
      if (id == 0) {
        if (fuo >= buf_size) {
          // Signal the commit handler to process the batch of proposals
          commit_barrier.arrive_and_wait();
          // Reset offset for the next batch
          fuo = 0;
        }
        exec();
        ++fuo;
      }
    }
  }
  handler_running.store(false, std::memory_order_relaxed);
  commit_handler.join();
  init();  // sync

  ROMULUS_INFO("Experiment is finished. Cleaning up...");

  done();  // cleanup

  if (id == (int)system_size - 1) {
    calc(outfile);
    calc = CALC_THROUGHPUT;
    calc(outfile);
  }

  outfile.close();

  for (auto& p : proposals) {
    delete[] p.second;
  }

  return 0;
}